trying to include new thresh~ object
working on this by having the code of Clip~ and sah~ as guides, merging
together structures from both of them. But there seems to be a conflict
and I can’t get it to compile. I’m getting the errors

“
sickle/thresh.c:29:23: error: use of undeclared identifier 'x'
    t_float lastout = x->x_lastout;
                      ^
sickle/thresh.c:39:5: error: use of undeclared identifier 'x'
    x->x_lastout = lastout;
    ^
”

but the same code in sah~ has no such issues.